# Site settings
title: Random musings...
email: colin@colinyates.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A collection of musics about Software Engineering and the madness of turning ambiguous specs into 0s and 1s.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://colinyates.co.uk" # the base hostname & protocol for your site
twitter_username: yatesco
github_username:  yatesco

# Build settings

# prefer /blog/y-m-d-my-post over /y/m/d/my-post so relative links
# (../images) works from org mode. This is a cheat, but because 'posts'
# and 'images' are siblings in _org relative links are reflected in the
# published article. This means that /ABC/ will load an image from
# /images/.
# (remember that jekyll produces a trailing slash)
permalink: /:year-:month-:day-:title
markdown: kramdown
